development:
    driver: postgres
    connstr: dbname=cwfy sslmode=disable 
    
staging:
    driver: postgres
    connstr: dbname=cwfy sslmode=disable user=ec2-user

production:
    driver: postgres
    connstr: dbname=cwfy-production sslmode=disable user=ec2-user