development:
    driver: postgres
    connstr: dbname=cwfy sslmode=disable
    
staging:
    driver: postgres
    connstr: dbname=cwfy sslmode=disable

production:
    driver: postgres
    connstr: dbname=cwfy-production sslmode=disable