ALTER TABLE service_requests
	ALTER COLUMN requested_datetime TYPE TIMESTAMP WITH TIME ZONE,
	ALTER COLUMN updated_datetime TYPE TIMESTAMP WITH TIME ZONE,
	ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
	ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
	ALTER COLUMN closed_datetime TYPE TIMESTAMP WITH TIME ZONE;